### PR TITLE
Prepare anorm-docs project for Scala 3

### PR DESCRIPTION
**Pull request by mkurz**
This way the "Dependency Graph" workflow should become green as soon as we release a Play 2.9 version / milestone with Scala 3 artifacts: https://github.com/playframework/anorm/actions/workflows/dependency-graph.yml

### CODE REVIEW

**Review by cchantep — APPROVED** [review]

**Comment by mkurz** [comment]
@cchantep whenevery you have time, can you take a look at the error when docs get compiled with Scala 3?
```
[error] -- Error: /home/runner/work/anorm/anorm/docs/manual/working/scalaGuide/main/sql/code/MacroToParameters.scala:60:28 
[error] 60 |    Macro.toParameters("#", Macro.ParameterProjection("bar", "lorem"))
[error]    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    | Expected a known value. 
[error]    |
[error]    | The value of: projection$proxy3
[error]    | could not be extracted using scala.quoted.FromExpr$SeqFromExpr@4bfe502c
[error] one error found
[error] (docs / Test / compileIncremental) Compilation failed
````
I don't want to spent too much time with anorm right now so would be happy if you check. Thanks!

**Comment by ihostage** [comment]
Hi, @cchantep! Can you finish this PR to release a final version Anorm that supports a `pekko-stream` (#572)?

**Comment by gaeljw** [comment]
Can we help somehow to move forward a release including `pekko-stream` support?

**Comment by mkurz** [comment]
> Can we help somehow to move forward a release including `pekko-stream` support?

@gaeljw (or whoever wants to help) you could take this pull request as base and try to get things work, also see hints in https://github.com/playframework/anorm/pull/537#issuecomment-1507197887

Currently, I will not spend time on this pull request, so community help is desired.

**Pull request merged**
