### PR TITLE
Renamed files Highights26/Migration26 to Highlights30/Migration30

### PR DESCRIPTION
**Pull request by dotta**
Because the current version of master is 3.0.0-SNAPSHOT, both the highlights and
migration files have been renamed accordingly.

### CODE REVIEW

**Comment by cchantep** [comment]
Hi @dotta , as far as I remember the discussion with @jroper , the Anorm roadmap no longer follow the Play release cycle?

**Comment by dotta** [comment]
@cchantep That's right, but I'm not sure what you are implying :-) anorm master is now on version 3.0.0-SNAPSHOT, and there hasn't been an anorm 2.6.0 release, that's why I thought the two files in this PR should be renamed with the `30` suffix. But maybe I got that wrong...

**Comment by cchantep** [comment]
I'm just surprised Anorm has been also moved to 3.0, I though the next release would be 2.6.

**Comment by dotta** [comment]
@cchantep The rationale for me was that since `anorm-iteratess` depends on `play-iteratess` (see [here](https://github.com/playframework/anorm/blob/master/build.sbt#L46)), and because Play 2.5 is not binary compatible with Play 2.4, to release anorm for Play 2.5 I had to bump the major version since we are following [semantic versioning](http://semver.org/). I hope I didn't get that wrong.

**Comment by dotta** [comment]
@jroper ping

**Comment by cchantep** [comment]
Hi, I would close this one for now.

**Comment by cchantep** [comment]
Hi, I would close this one for now.

**Comment by cchantep** [comment]
Hi, I would close this one for now.

**Pull request closed without merging**
